#!/usr/bin/env perl
use Mojolicious::Lite;

# Documentation browser under "/perldoc"
plugin 'PODRenderer';

get '/' => sub {
  my $c = shift;
  $c->render(template => 'index');
};

app->start;
__DATA__

@@ index.html.ep
<!DOCTYPE html>
    <html>
    <head>
        %= javascript 'http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'
        %= javascript begin
        	$(document).ready(function() {
    		var max_fields      = 10; //maximum input boxes allowed
    		var wrapper         = $(".input_fields_wrap"); //Fields wrapper
    		var add_button      = $(".add_field_button"); //Add button ID
 		   	var x = 1; //initlal text box count
    		$(add_button).click(function(e){ //on add input button click
        	e.preventDefault();
        	if(x < max_fields){ //max input box allowed
            x++; //text box increment
            $(wrapper).append('<div><input type="text" name="mytext[]"/><a href="#" class="remove_field">Remove</a></div>'); //add input box
        }
    });
   
    $(wrapper).on("click",".remove_field", function(e){ //user click on remove text
        e.preventDefault(); $(this).parent('div').remove(); x--;
    })
});

            % end
    </head>
    <body>
	
        %= form_for go => begin
        %= image '/plus.png'
	<div class="input_fields_wrap">
    <button class="add_field_button" img = 'plus.png'>Add More Fields</button>
    <div><input type="text" name="mytext[]"></div>
	</div>
        %= submit_button "Submit"
        % end
    </body>
    </html>
